name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 UTC on Sun.

permissions:
  contents: read

jobs:
  #########################
  # Run PHPUnit testsuite #
  #########################
  testsuite:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
        db-type: [mysql]
        prefer-lowest: ['', 'prefer-lowest']

    steps:
    - uses: actions/checkout@v3

    - name: Setup MySQL 8
      if: matrix.db-type == 'mysql'
      run: |
          sudo service mysql start
          mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE pagination;'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Get date part for cache key
      id: key-date
      run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: test-${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.prefer-lowest }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl

    - name: Install composer dependencies
      run: |
        if ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
          composer update --prefer-lowest --prefer-stable
        elif ${{ matrix.php-version == '8.2' }}; then
          composer update --ignore-platform-req=php
        else
          composer update
        fi

    - name: Run PHPUnit testsuite
      run: |
        if [[ ${{ matrix.db-type }} == 'mysql' ]]; then
          export DB_URL='mysql://root:root@127.0.0.1/pagination';
          mysql -h 127.0.0.1 -u root -proot pagination < ./tests/Schema/articles.sql
        fi
        vendor/bin/phpunit --stderr;

  ##############
  # Code style #
  ##############
  cs:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Get date part for cache key
      id: key-date
      run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: cs-${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.prefer-lowest }}
        restore-keys: |
          cs-${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.prefer-lowest }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl

    - name: Install composer dependencies
      run: composer update --no-interaction

    - name: Run CS check
      run: composer cs-check
